colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = false
enableSearch = false
enableCodeCopy = false
replyByEmail = false
disableImageZoom = false
disableImageOptimization = false
disableTextInHeader = false
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"

[header]
layout = "fixed-fill"

[footer]
showMenu = true
showCopyright = false
showThemeAttribution = true
showAppearanceSwitcher = false
showScrollToTop = true

[homepage]
layout = "custom"
showRecent = false
showRecentItems = 6
showMoreLink = true
showMoreLinkDest = "/posts/"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = false

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = true
showAuthor = false
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = true
showReadingTime = false
showTableOfContents = false
showTaxonomies = true
showAuthorsBadges = false
showWordCount = false
showZenMode = false

[list]
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = false
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
orderByWeight = false
groupByYear = true
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = true

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = true
cardView = true
cardViewScreenWidth = false
heroStyle = ""

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[selineAnalytics]

[buymeacoffee]

[verification]
